#!/bin/bash

# Navigate to the directory containing the scripts
cd ~/.dotfiles/githooks/

# Only attempt to restore from backup if the current active script is not already the original
if [[ -f prepare-commit-msg-backup && ! -f prepare-commit-msg-james ]]; then
    mv prepare-commit-msg prepare-commit-msg-james
    echo "Current file renamed to James version."
fi

# Restore the original from backup if it's not already restored
if [[ -f prepare-commit-msg-backup && ! -f prepare-commit-msg ]]; then
    mv prepare-commit-msg-backup prepare-commit-msg
    echo "Original version restored."
else
    echo "No changes needed. Original version is already active or missing files."
fi
