# NOTE:
# docs:
# ghostty +show-config --default --docs | vim
# examples:
# https://github.com/search?q=path%3Aghostty%2Fconfig&type=code
# ghostty +list-fonts

# https://ghostty.zerebos.com/settings/application

auto-update-channel = tip

font-size = 20

# monospace
font-family = "JetBrains Mono"
font-family-bold = "JetBrains Mono"

maximize = true
clipboard-read = allow
clipboard-write = allow

# italics
# https://github.com/subframe7536/maple-font
font-family-italic = "Maple Mono"
font-variation-italic = wght=200
font-family-bold-italic = "Maple Mono"
font-variation-bold-italic = wght=800

window-title-font-family = "JetBrains Mono"

alpha-blending = linear-corrected

macos-titlebar-style = tabs
macos-titlebar-proxy-icon = hidden
macos-option-as-alt = true

background-opacity = 0.96
background-blur-radius = 40

# ghostty +list-themes
# theme = dark:/path/to/dark/theme,light:/path/to/light/theme

mouse-hide-while-typing = true

window-inherit-working-directory = false
working-directory = home

# keymaps
keybind = shift+enter=text:\n
keybind = alt+backspace=text:\x1b\x7f

# shader
# - https://github.com/hackr-sh/ghostty-shaders
# custom-shader = /path/to/ghostty-shaders/cursor_blaze.glsl
# custom-shader-animation = false
