# Homebrew package manifest for ~/.dotfiles
# Install/update everything with:
#   brew bundle --file ~/.dotfiles/Brewfile

# Taps
# Custom taps used by a handful of formulas below.
tap "heroku/brew"
tap "gdubw/gng"
tap "remotemobprogramming/brew"
tap "anchore/grype"
tap "rhysd/actionlint", "https://github.com/rhysd/actionlint"
tap "tobi/try", "https://github.com/tobi/try"

# Core / shell tooling
brew "coreutils"
brew "gnu-sed"
brew "wget"
brew "vim"
brew "openssh"
brew "openssl"
brew "make"
brew "nano"
brew "perl"
brew "ripgrep"
brew "git"
brew "curl"
brew "jq"
brew "bat"
brew "eza"
brew "tree"
brew "gh"
brew "fd"
brew "fzf"
brew "tmux"

# Dev tools
brew "heroku"
brew "gradle"
brew "gng"
brew "maven"
brew "gcc"
brew "hugo"
brew "yamllint"
brew "vale"
brew "scc"
brew "ast-grep"
brew "yq"
brew "poppler"
brew "mob"
brew "rbenv"
brew "terraform"
brew "oci-cli"
brew "actionlint"
brew "uv"
brew "n"
brew "try"
brew "go"
brew "golangci-lint"
brew "xcodegen"
brew "swift-format"
brew "swiftlint"
brew "xcbeautify"

# Utilities
brew "htop"
brew "telnet"
brew "nmap"
brew "gping"
brew "ffmpeg"
brew "tesseract"
brew "yt-dlp"
brew "grype"
