#!/bin/bash
FILE=$1
MESSAGE=$(cat $FILE)
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '^(\w+/)?\w+[-_][0-9]+' | grep -Eo '\w+[-][0-9]+' | tr "[:lower:]" "[:upper:]")

# Define the Co-Author information
CO_AUTHOR="\n\nCo-Authored-By: James Skarzinskas <james@jskarzin.org>"

if [[ $TICKET == "" ]]; then
  echo 'Branch name without ticket information, keeping git message as is.'
  exit 0;
fi
if [[ $MESSAGE == "Merge"* ]]; then
  echo 'Merge commit, keeping git message as is.'
  exit 0;
fi
if [[ "$MESSAGE" == "$TICKET"* ]]; then
  echo 'Ticket information already present, keeping git message as is.'
  exit 0;
fi

# Append ticket information and co-author information
echo "$TICKET $MESSAGE" > $FILE
echo "$CO_AUTHOR" >> $FILE
