#!/bin/bash

# Navigate to the directory containing the scripts
cd ~/.dotfiles/githooks/

# Check if the backup already exists to avoid overwriting
if [[ ! -f prepare-commit-msg-backup && -f prepare-commit-msg ]]; then
    mv prepare-commit-msg prepare-commit-msg-backup
    echo "Original file backed up."
fi

# Rename prepare-commit-msg-james to prepare-commit-msg if the latter isn't already the james version
if [[ -f prepare-commit-msg-james && ! -f prepare-commit-msg ]]; then
    mv prepare-commit-msg-james prepare-commit-msg
    echo "James version activated."
else
    echo "No changes needed. James version is already active or missing files."
fi
