#!/usr/bin/env bash
# Show the most frequently changed files in the last 12 months.

set -euo pipefail

git log --format=format: --name-only --since=12.month \
 | grep -E -v '^$' \
 | sort \
 | uniq -c \
 | sort -r \
 | head -50

