#!/usr/bin/env bash
# Print the current clipboard contents to stdout.

set -euo pipefail

if command -v pbpaste >/dev/null 2>&1; then
  exec pbpaste
elif command -v xclip >/dev/null 2>&1; then
  exec xclip -selection clipboard -o
else
  echo 'cannot find a paste program' >&2
  exit 1
fi
