#!/usr/bin/env bash
# Format SQL using the sqlformat.org API.

set -euo pipefail

curl -s --location --request POST 'https://sqlformat.org/api/v1/format' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'reindent=1' \
  --data-urlencode 'indent_width=3' \
  --data-urlencode 'keyword_case=upper' \
  --data-urlencode 'strip_comments=1' \
  --data-urlencode "sql=$1" | jq -r '.result'

