#!/bin/bash

# Global hook logic
FILE=$1
MESSAGE=$(cat $FILE)
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '^(\w+/)?\w+[-_][0-9]+' | grep -Eo '\w+[-][0-9]+' | tr "[:lower:]" "[:upper:]")

# Define the Co-Author information
CO_AUTHOR=$'\n\n\nCo-Authored-By: James Skarzinskas <james@jskarzin.org>'

if [[ $TICKET == "" ]]; then
  echo 'Branch name without ticket information, keeping git message as is.'
else
  if [[ $MESSAGE == "Merge"* ]]; then
    echo 'Merge commit, keeping git message as is.'
  elif [[ "$MESSAGE" == "$TICKET"* ]]; then
    echo 'Ticket information already present, keeping git message as is.'
  else
    # Prepend the ticket information only if conditions are met
    echo "$TICKET $MESSAGE" > $FILE
  fi
fi

# Append Co-Author information unconditionally
echo "$CO_AUTHOR" >> $FILE

echo 'Co-author information added.'

# Execute local hook if it exists
LOCAL_HOOK="$(git rev-parse --git-dir)/hooks/prepare-commit-msg"
if [[ -x "$LOCAL_HOOK" ]]; then
  exec "$LOCAL_HOOK" "$@"
fi
